
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotevent
    username: root
    password: ok
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.s3.mapper: debug
  config: classpath:lombok-spring.xml